name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag python-mooping:$(date +%s)
    - name: Push to github
      run: git add . && git pull && git add . && git commit -m "Docker Image Build Successfully" && git push
